### ISSUE TITLE
Doesn't load dynamically added images

### ISSUE THREAD

**Issue by justas-kuizinas** [tjoskar/ng2-lazyload-image#102]
For example I have list of comments where each comment consists of image, name, lastname, comment, date. When I open page and scroll down everything is ok images are lazyloaded, but when I insert comment dynamically image doesn't load  but has class "ng2-lazyloaded"

![localhost_8100 - google chrome 2017-02-02 17 09 46](https://cloud.githubusercontent.com/assets/5862640/22554915/8ea47110-e96a-11e6-8fa8-f8990006cb84.png)

**Comment by tjoskar** [comment]
Hum.. that's weird. 
Just to be clear, is the base64 image in your example above your default image?

**Comment by justas-kuizinas** [comment]
Yes it's base64. My html looks like this. 

<ion-item *ngFor="let comment of comments; let last = last" class="_comment" mode="primary">
        <ion-avatar item-left>
            <img [attr.src]="base64Image" [lazyLoad]="comment.User.Photo?.Url" [scrollObservable]="content.ionScroll"/>
        </ion-avatar>
        <h2>{{comment.User?.Name}} {{comment.User?.LastName}}</h2>
        <p>
            {{comment.Comment}}
        </p>
        <hd-time [time]="comment.CreatedAt"></hd-time>
        <span style="width:0;height: 0;overflow: hidden" *ngIf="last && commented">{{scrollBottom()}}</span>
    </ion-item>

**Comment by tjoskar** [comment]
Is `comment.User.Photo?.Url` loaded asynchronous? Can you try to wrap your image tag into a if statement before I start investigating the problem, i.e.
```html
<ion-avatar item-left>
  <template [ngIf]="comment.User.Photo?.Url">
    <img [attr.src]="base64Image" [lazyLoad]="comment.User.Photo?.Url" [scrollObservable]="content.ionScroll"/>
  </template>
</ion-avatar>
```

**Comment by justas-kuizinas** [comment]
Everything is working now

**Comment by tjoskar** [comment]
Okay, so I guess something like this is happening:
1. You create an image-tag
2. lazyload-image-directive initialize
3. `comment.User.Photo?.Url` evaluates to null for some reason
4. The images is in viewport so it tries to load `comment.User.Photo?.Url` but fails because it's null
5. lazyload-image-directive thinks it's done and unsubscribe
6. `comment.User.Photo?.Url` is now a valid path to an image but the directive do no longer cares.

But if we wrap the image-tag within a if statement that checks if we have a image the problem will not occur.

We could solve the problem by delaying the subscription until we have a lazyload image. I think this pull request would solve your problem: https://github.com/tjoskar/ng2-lazyload-image/pull/64#issuecomment-258772802 I will accept it if you create a new pull request.

**Comment by tjoskar** [comment]
When I think about it...
The pull request will not solve your problem because we have to trigger a scroll event when the lazyloadimage is updated :/

I think the best solution right now is to use a if statement. If you don't like the `template`-tag you should be able to use `*ngIf` instead:
```html
<ion-avatar item-left>
  <img *ngIf="comment.User.Photo?.Url" [attr.src]="base64Image" [lazyLoad]="comment.User.Photo?.Url" [scrollObservable]="content.ionScroll"/>
</ion-avatar>
```

Please feel free to reopen the issue if you like.

**Comment by dbarochia** [comment]
This issue is still open. It’s work with the static data but fails when I pull the information dynamic (using for loop from json)
Below code is behaving as per the expectation.

<ul id="lazyTest1">
    <li> <img lazyLoad="./audio/a/1J13CF/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
    <li> <img lazyLoad="./audio/a/1lH7NO/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
    <li> <img lazyLoad="./audio/p/90UOOL/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
    <li> <img lazyLoad="./audio/p/10ALUD/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
    <li> <img lazyLoad="./audio/a/EZRW17/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
    <li> <img lazyLoad="./audio/a/0Q8V5W/hqdefault.jpg" src="assets/images/loading.gif" />  </li>
</ul>


In this code, image always display src image it not get replaced with the LazyLoad image.
<ul id="lazyTest1">
    <li  *ngFor='let direct of sngDirect'>
        <img [attr.lazyLoad]="direct.hqImage" src="assets/images/loading.gif" />
    </li>
</ul>


Below is the html which get generated with above code.
<ul id="lazyTest1">
    
<li> <img src="assets/images/loading.gif" lazyload="./audio/a/1J13CF/hqdefault.jpg"> </li>
<li><img src="assets/images/loading.gif" lazyload="./audio/a/1lH7NO/hqdefault.jpg"></li>
<li><img src="assets/images/loading.gif" lazyload="./audio/p/90UOOL/hqdefault.jpg"></li>
<li><img src="assets/images/loading.gif" lazyload="./audio/p/10ALUD/hqdefault.jpg"></li>
<li><img src="assets/images/loading.gif" lazyload="./audio/a/EZRW17/hqdefault.jpg"></li>
<li><img src="assets/images/loading.gif" lazyload="./audio/a/0Q8V5W/hqdefault.jpg "></li>
</ul>


Please help me to resolve the problem.

**Comment by tjoskar** [comment]
@dbarochia, `lazyLoad` is not an attribute and you should therefore not use `[attr.lazyLoad]`. Can you try to use the following code:
```html
<ul id="lazyTest1">
  <li *ngFor='let direct of sngDirect'>
    <img [lazyLoad]="direct.hqImage" src="assets/images/loading.gif" />
  </li>
</ul>
```

**Comment by matthieu80** [comment]
@tjoskar 
Does it have to be a base64 image? would it be possible to have the file (like the "file:///" coming from image picker on a ionic mobile app)?
Thank you for your component, it is the best around!

**Comment by tjoskar** [comment]
@matthieu80, it doesn't have to be a base64 image. It can be anything the `img` tag understand: `file`, `http`, `url`, etc.. `ng-lazyload-image` will just take the string from the `lazyLoad` and `defaultImage` and put it in the `src` attribute.

**Comment by matthieu80** [comment]
@tjoskar Yes you are right. It was my mistake. Thank you very much!
