### ISSUE TITLE
Consuming output of build

### ISSUE THREAD

**Issue by plug-n-play** [tjoskar/ng2-lazyload-image#89]
Hello

'npm run build:example' produces the dist folder.

Shouldn't there be an output generated which can be deployed on a static server, i.e., a folder containing index.html, the transpiled JS files and the resources folder?

**Comment by tjoskar** [comment]
Hi,

> Shouldn't there be an ...
Maybe. The purpose of this projekt is to export a module that you can include in your angular project. If you want to run the example app, you can do so by running `npm start`. It will start a dev server and you can visit the example app at: http://localhost:9000/

But yeah, you are right. When you run `npm run build:example`, it should include a index.html as well. Right now you have to manually copy `/example/index.html` to `/dist/index.html`. It's not optimal and I gladly receives pull request if you have a good solution.

**Comment by tjoskar** [comment]
I updated the build script to copy index.html and style.css to the example dist. So if you do a pull and build the example app once again you should get a new folder, named: `example-dist`. You must however use a server due to the use of angular router. Eg. (if you have python installed):

```
$ git pull
$ npm install
$ npm run build:example
$ cd example-dist
$ python -m SimpleHTTPServer
```

Open your browser `http://localhost:8000`.
